import type { MediaItem } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const mockLibrary: MediaItem[] = [
  {
    id: '1',
    title: 'Cosmic Echoes',
    type: 'movie',
    summary: 'A lone astronaut discovers a mysterious signal from a distant galaxy, leading her on a perilous journey to uncover the origins of the universe.',
    posterUrl: PlaceHolderImages[0].imageUrl,
    cast: ['Aria Vance', 'Leo Cruz', 'Dr. Aris Thorne'],
    rating: 8.5,
    status: 'unwatched',
    genres: ['Science Fiction', 'Thriller'],
  },
  {
    id: '2',
    title: 'The Last Painter',
    type: 'movie',
    summary: 'In a world devoid of color, an elderly artist holds the last pigments. He must decide whether to share his gift or protect it from a monochrome society.',
    posterUrl: PlaceHolderImages[1].imageUrl,
    cast: ['Elias Thorne', 'Clara Belle', 'Marcus Grey'],
    rating: 9.1,
    status: 'watched',
    genres: ['Drama', 'Fantasy'],
  },
  {
    id: '3',
    title: 'Zero Protocol',
    type: 'movie',
    summary: 'A rogue agent is activated to stop a cyber-terrorist group from unleashing a digital plague that could collapse the global economy.',
    posterUrl: PlaceHolderImages[2].imageUrl,
    cast: ['Jax Ryder', 'Zara Khan', 'General Stone'],
    rating: 7.8,
    status: 'in-progress',
    genres: ['Action', 'Thriller'],
  },
  {
    id: '4',
    title: 'The Pineapple Incident',
    type: 'movie',
    summary: 'Two bumbling detectives accidentally get entangled with a crime syndicate after a mix-up involving a pineapple and a briefcase full of cash.',
    posterUrl: PlaceHolderImages[3].imageUrl,
    cast: ['Milo Fitz', 'Penny Lane', 'Don "The Juice" Mango'],
    rating: 7.2,
    status: 'unwatched',
    genres: ['Comedy', 'Crime'],
  },
  {
    id: '5',
    title: 'Aethelgard',
    type: 'series',
    summary: 'A historical epic chronicling the rise of a young shieldmaiden who unites warring clans to defend their homeland from a formidable invading empire.',
    posterUrl: PlaceHolderImages[4].imageUrl,
    cast: ['Freya Ironside', 'Bjorn Lothar', 'King Alaric'],
    rating: 8.9,
    status: 'watched',
    genres: ['History', 'Drama', 'Action'],
  },
  {
    id: '6',
    title: 'The Crystal Key',
    type: 'series',
    summary: 'In a realm powered by magic, a group of young mages must find the legendary Crystal Key to restore balance before their world is consumed by shadow creatures.',
    posterUrl: PlaceHolderImages[5].imageUrl,
    cast: ['Lyra Meadowlight', 'Kaelen Shadowhand', 'Elara the Wise'],
    rating: 8.2,
    status: 'in-progress',
    genres: ['Fantasy', 'Adventure'],
  },
  {
    id: '7',
    title: 'Orion\'s Belt',
    type: 'series',
    summary: 'The crew of the starship Orion navigates the treacherous outer belt, smuggling goods and dodging the authoritarian Galactic Federation.',
    posterUrl: PlaceHolderImages[6].imageUrl,
    cast: ['Captain Eva Rostova', 'Jax "The Fixer" Smith', 'Nova'],
    rating: 8.7,
    status: 'unwatched',
    genres: ['Science Fiction', 'Adventure'],
  },
  {
    id: '8',
    title: 'Wild Frontiers',
    type: 'movie',
    summary: 'A breathtaking documentary exploring the most remote and untouched ecosystems on Earth, revealing the secret lives of its unique inhabitants.',
    posterUrl: PlaceHolderImages[7].imageUrl,
    cast: ['Narrated by David Attenborough'],
    rating: 9.5,
    status: 'watched',
    genres: ['Documentary', 'Nature'],
  },
];
